// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkRbpUSk2yRxLL7cDbYdRgMYYK_7SAw-A',
    appId: '1:459443760553:web:635017ae6df015bced28b8',
    messagingSenderId: '459443760553',
    projectId: 'santuy-project-flutter',
    authDomain: 'santuy-project-flutter.firebaseapp.com',
    storageBucket: 'santuy-project-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVxgUzlOIumQGD_6OOG2zLOCJ0reRyc8E',
    appId: '1:459443760553:android:c8ca21f265f0e001ed28b8',
    messagingSenderId: '459443760553',
    projectId: 'santuy-project-flutter',
    storageBucket: 'santuy-project-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8VjVuwo2GUCjh3zCiiJrlQLpYkAr_qQ',
    appId: '1:459443760553:ios:eefe84fde6372135ed28b8',
    messagingSenderId: '459443760553',
    projectId: 'santuy-project-flutter',
    storageBucket: 'santuy-project-flutter.appspot.com',
    iosClientId:
        '459443760553-jc91pmk3u8f7dn9sk4uku8dg1gplr4lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalSantuy',
  );
}
